language: rust
sudo: false
rust:
- stable
- beta
- nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libzmq3-dev
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo build
- travis-cargo test
- travis-cargo bench
- travis-cargo build -- --example msgsend
- travis-cargo build -- --example helloworld_client
- travis-cargo build -- --example helloworld_server
- travis-cargo build -- --example version
- travis-cargo build -- --example weather_client
- travis-cargo build -- --example weather_server
- travis-cargo build -- --example taskvent
- travis-cargo build -- --example taskwork
- travis-cargo build -- --example tasksink
- travis-cargo build -- --example msreader
- travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo coveralls --no-sudo
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: HsoFtb8raiT2SJewpTEOFeMgXZUOwbcBEcjVPlsyrBI8WZ9dGp3aK1k6MsfiF4AV6PVE3XaaEQS/9iks5l4YswHP0WGz2L2hV2CORMem25x3q85PWZzZFm4RdO6E13LDRHjRZ56u80rYs0koL7loY2AZxc1iibwyKfUwba1LYu8=
