[package]
name = "zmq"
version = "0.6.2"
authors = [ "erick.tryzelaar@gmail.com" ]
license = "MIT/Apache-2.0"
description = "High-level bindings to the zeromq library"
repository = "https://github.com/erickt/rust-zmq"

[[example]]
name = "msgsend"
path = "examples/msgsend/main.rs"

[[example]]
name = "helloworld_client"
path = "examples/zguide/helloworld_client/main.rs"

[[example]]
name = "helloworld_server"
path = "examples/zguide/helloworld_server/main.rs"

[[example]]
name = "version"
path = "examples/zguide/version/main.rs"

[[example]]
name = "weather_client"
path = "examples/zguide/weather_client/main.rs"

[[example]]
name = "weather_server"
path = "examples/zguide/weather_server/main.rs"

[dependencies]
time = "*"
rand = "*"
zmq-sys = "0.6.2"
