[package]
name = "zmq"
version = "0.5.2"
authors = [ "erick.tryzelaar@gmail.com" ]

[[example]]
name = "msgsend"
path = "examples/msgsend/main.rs"

[[example]]
name = "helloworld-client"
path = "examples/zguide/helloworld-client/main.rs"

[[example]]
name = "helloworld-server"
path = "examples/zguide/helloworld-server/main.rs"

[[example]]
name = "version"
path = "examples/zguide/version/main.rs"

[[example]]
name = "weather-client"
path = "examples/zguide/weather-client/main.rs"

[[example]]
name = "weather-server"
path = "examples/zguide/weather-server/main.rs"

[dependencies.time]
git = "https://github.com/rust-lang/time"
